### ISSUE TITLE
upgrade minor Python version

### ISSUE THREAD

**Issue by slinshady89** [SICKAG/ScanSegmentAPI#3]
Can you upgrade your minor python version in the project so one can use it with poetry and also matplotlib? 

Unfortunately matplotlib requires at least Python 3.10

I would be very graceful for your support

**Comment by weinmalSICKAG** [comment]
Thank you for your feedback.
We set the version range to ^3.9. This should not prohibit using ScanSegmentAPI with Python 3.10.

**Comment by weinmalSICKAG** [comment]
How do you include scansegmentapi in your project?
Could you please provide a more detailed explanation of the error you get. For example the console output.

**Comment by slinshady89** [comment]
![Image](https://github.com/user-attachments/assets/6d02f14f-6302-417a-8aac-9510aa0bab18)

for example it works to add pandas, but not to add matplotlib. 
If I do a https clone into my project, then add your package not via URL but by path it also fails do add matplotlib. 
However, adapting the minimum Python Version from ^3.9 to ^3.10 helps as a workaround.

**Comment by weinmalSICKAG** [comment]
Thank you for the additional information. I will try to reproduce the error and come back with a solution that works for you.

**Comment by weinmalSICKAG** [comment]
I was able to reproduce the error.
The allowed versions of Python before adding matplotlib are `^3.9,<4.0`. By adding matplotlib the Python version range would be restricted to `^3.10,<4.0`. This results in an error. This can be fixed by setting the python version range of `sick-eval` to `^3.10`. For poetry 1.8.3 the `pyproject.toml` file looks like this:
```toml
[tool.poetry]
name = "sick-eval"
version = "0.1.0"
description = ""
authors = ["Alexander Weinmann"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "2.2.3"
scansegmentapi = {path = "../scansegmentapi"}
matplotlib = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Let me know if this fixes your issue.
